kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-storageclass
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  shared: "false"
  priority_io: "high"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: px-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: jenkins
spec:
 selector:
    matchLabels:
      app: jenkins-app
 replicas: 1
 template:
  metadata:
   labels:
    app: jenkins-app
  spec:
   schedulerName: stork
   securityContext:
     fsGroup: 1000
   containers:
   - name: jenkins
     imagePullPolicy: IfNotPresent
     image: jenkins/jenkins:lts
     ports:
     - containerPort: 8080
     volumeMounts:
       - mountPath: /var/jenkins_home
         name: jenkins-home
   volumes:
     - name: jenkins-home
       persistentVolumeClaim:
         claimName: jenkins-claim
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-app
  type: NodePort
